### PR TITLE
add support for arbitrary fields on ACF

### PR DESCRIPTION
**Pull request by rburgst**
- this now allows adding custom registration for custom GraphQL types
   e.g. ACF fields on a post

### CODE REVIEW

**Comment by rburgstaller** [comment]
anyone home?

**Comment by progital** [comment]
Thanks for the PR, awesome work!

**Comment by rburgst** [comment]
thanks for merging, when can I expect a new release?

**Comment by progital** [comment]
I can't get the new version (merged your latest PR #29) to work in my test environment. Does it work for you?

**Comment by rburgst** [comment]
nope, I believe the problem is that the api for `gatsby-plugin-sharp` has changed and if you now have a newer version I get

```
Gatsby-plugin-sharp wasn't setup correctly in gatsby-config.js. Make sure you add it to the plugins array.
```

**Comment by rburgst** [comment]
actually it works with plugin-sharp <= 2.4.4

```
  "dependencies": {
    "@babel/runtime": "^7.0.0",
    "@emotion/core": "^10.0.14",
    "@mdx-js/react": "^1.0.27",
    "cheerio": "^1.0.0-rc.3",
    "gatsby": "^2.20.25",
    "gatsby-image": "^2.3.4",
    "gatsby-plugin-sharp": "<=2.4.4",
```

However, I believe there is a bug in the implementation that makes it no longer compatible with more recent versions.

**Comment by rburgst** [comment]
arg, just noticed that I introduced a bug in the parsing (however the problem with plugin-sharp is something different).

**Pull request merged**
