### PR TITLE
Avoid racing conditions and repetitive processing when pages are cross-referenced

### PR DESCRIPTION
**Pull request by sarutole**
Without this fix, rebuild time was growing exponentially with every new post.

### CODE REVIEW

**Comment by progital** [comment]
Hi!
Thanks for the PR. Could you elaborate on the issue this PR aims to solve?

**Comment by sarutole** [comment]
Let's say you have 10 posts total. Every post can have up to 8 related posts that show up in a dedicated section (the numbers are arbitrary, just for illustration). Effectively, there are a lot of cross-references among those pages. 

The fragment to fetch that data could be like this:
```
fragment PostTemplateFragment on WPGraphQL_Post { 
    postId
    title
    content
    acf {
      relatedPosts {
        ... on WPGraphQL_Post {
          postId
          title
          content
        }
      }
    }
  }
```

This plugin attempts to parse `content` everywhere it sees it. When there are a lot of cross-references among posts, there is often a situation where the plugin starts parsing the same content multiple times and then initiate duplicate downloads of the same images. This PR is to prevent parsing the same content many times and to prevent downloading and processing the same images numerous times which takes much longer than necessary. With this optimization, my site (~30 posts) rebuilds 4x faster (~1min rather than 4mins). Without the optimization, rebuild takes significantly longer with every new post.

**Review by progital — APPROVED** [review]

**Comment by progital** [comment]
Thanks, merging the PR. I'll refactor it a bit because, for example, I avoid using `else` statements.

**Comment by progital** [comment]
Hey @sarutole . I refactored the resolver using promises as it fits the idea of avoiding racing conditions better. What do you think? Could you test it? I haven't published it yet.
d1c4f34defe898e1f0e3bccc9584f424c01669a5

**Comment by sarutole** [comment]
@progital sorry for the late response. The new version works as intended. Thanks for the update!

**Comment by progital** [comment]
Published the new version.

**Pull request merged**
